sudo: required
services:
  - docker

before_install:
  - docker build -t trungtx92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trungtx92/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReactTravisCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-864591160546"
  bucket_path: "docker-react-travis-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY